/*
 * TheorySuite.java
 * JUnit based test
 *
 * Created on April 1, 2008, 11:04 PM
 */

package nii.alloe.theory;

import junit.framework.*;

/**
 *
 * @author john
 */
public class TheorySuite extends TestCase {
    
    public TheorySuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("TheorySuite");
        suite.addTest(nii.alloe.theory.LogicTest.suite());
        suite.addTest(nii.alloe.theory.SpecificGraphTest.suite());
        suite.addTest(nii.alloe.theory.RuleTest.suite());
        suite.addTest(nii.alloe.theory.EquivalenceGraphTest.suite());
        suite.addTest(nii.alloe.theory.MembershipGraphTest.suite());
        suite.addTest(nii.alloe.theory.ProbabilityGraphTest.suite());
        suite.addTest(nii.alloe.theory.ModelTest.suite());
        return suite;
    }
    
}
