/* Generated By:JavaCC: Do not edit this line. AlloeTokenizerConstants.java */
package nii.alloe.corpus.analyzer;

public interface AlloeTokenizerConstants {

  int EOF = 0;
  int ALPHANUM = 1;
  int PUNCSEQ = 2;
  int APOSTROPHE = 3;
  int ACRONYM = 4;
  int COMPANY = 5;
  int EMAIL = 6;
  int HOST = 7;
  int NUM = 8;
  int P = 9;
  int HAS_DIGIT = 10;
  int ALPHA = 11;
  int LETTER = 12;
  int NONWS = 13;
  int CJ = 14;
  int KOREAN = 15;
  int DIGIT = 16;
  int NOISE = 17;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<ALPHANUM>",
    "<PUNCSEQ>",
    "<APOSTROPHE>",
    "<ACRONYM>",
    "<COMPANY>",
    "<EMAIL>",
    "<HOST>",
    "<NUM>",
    "<P>",
    "<HAS_DIGIT>",
    "<ALPHA>",
    "<LETTER>",
    "<NONWS>",
    "<CJ>",
    "<KOREAN>",
    "<DIGIT>",
    "<NOISE>",
  };

}
