/*
 * ClassifySuite.java
 * JUnit based test
 *
 * Created on 08 January 2008, 12:52
 */

package nii.alloe.classify;

import junit.framework.*;

/**
 *
 * @author john
 */
public class ClassifySuite extends TestCase {
    
    public ClassifySuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("ClassifySuite");
        suite.addTest(nii.alloe.classify.DataSetTest.suite());
        return suite;
    }
    
}
