/*
 * AlloeMain.java
 *
 * Created on 09 January 2008, 16:57
 */

package nii.alloe.gui;

import javax.swing.*;
import javax.swing.table.*;
import java.io.*;
import java.util.*;
import java.text.*;
import nii.alloe.classify.*;
import nii.alloe.corpus.*;
import nii.alloe.corpus.pattern.*;
import nii.alloe.niceties.*;
import weka.classifiers.*;
import weka.core.*;

/**
 *
 * @author  john
 */
public class AlloeMain extends javax.swing.JFrame {
    private Corpus corpus;
    
    private String corpusTextFile;
    private String corpusTermSetFile;
    private String corpusIndexFile;
    private CorpusLoader corpusLoader;
    private JFileChooser fileChooser;
    private CorpusLoaderProgressListener clProgListener;
    private PatternGeneratorListener pbListener;
    private FeatureVectorListener fvListener;
    private HashMap<String, String> termSetFileName;
    private HashMap<String, String> fvTermSetFileName;
    private HashMap<String, PatternBuilder> patternBuilderProcess;
    private HashMap<String, FeatureVectorFormer> featureVectorProcess;
    private HashMap<String, PatternSet> patternSets;
    private DataSet dataSet;
    
    private AlloeMain thisForAnon;
    
    /** Creates new form AlloeMain */
    public AlloeMain() {
        initComponents();
        corpusTextFile = corpusTermSetFile = corpusIndexFile = "";
        fileChooser = new JFileChooser();
        thisForAnon = this;
        corpusDisplayTableModel = new CorpusTableModel();
        termSetFileName = new HashMap<String,String>();
        fvTermSetFileName = new HashMap<String,String>();
        patternBuilderProcess = new HashMap<String,PatternBuilder>();
        featureVectorProcess = new HashMap<String,FeatureVectorFormer>();
        patternSets = new HashMap<String,PatternSet>();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        corpusAction = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        openCorpusTextFile = new javax.swing.JButton();
        openCorpusTermSet = new javax.swing.JButton();
        textFileLabel = new javax.swing.JLabel();
        termSetLabel = new javax.swing.JLabel();
        indexerProgressMonitor = new nii.alloe.gui.ProcessMonitor();
        if(clProgListener == null)
        clProgListener = new CorpusLoaderProgressListener();
        indexerProgressMonitor.addExtraListener(clProgListener);
        indexLocationLabel = new javax.swing.JLabel();
        setIndexButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        openIndexedCorpus = new javax.swing.JButton();
        saveIndexedCorpus = new javax.swing.JButton();
        corpusDisplayScroll = new javax.swing.JScrollPane();
        corpusDisplay = new javax.swing.JTable();
        corpusTotalLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        termPairSetLabel = new javax.swing.JLabel();
        openTermPairSet = new javax.swing.JButton();
        patternGeneratorRelationship = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        patternGeneratorProgressMonitor = new nii.alloe.gui.ProcessMonitor();
        if(pbListener == null)
        pbListener = new PatternGeneratorListener();
        patternGeneratorProgressMonitor.addExtraListener(pbListener);
        patternBuilderMetric = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        patternViewerRelationshipLabel = new javax.swing.JLabel();
        patternViewerRelationship = new javax.swing.JComboBox();
        openPatternSet = new javax.swing.JButton();
        savePatternSet = new javax.swing.JButton();
        totalPatternsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        patternTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        featureVectorRelationship = new javax.swing.JComboBox();
        openDataSet = new javax.swing.JButton();
        saveDataSet = new javax.swing.JButton();
        featureVectorFormerMonitor = new nii.alloe.gui.ProcessMonitor();
        featureVectorTermPairLabel = new javax.swing.JLabel();
        featureOpenTermPairs = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        wekaOutput = new javax.swing.JTextArea();
        classifier = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        classifierParameters = new javax.swing.JTextField();
        saveClassifierButton = new javax.swing.JButton();
        openClassifierButton = new javax.swing.JButton();
        startTrainingButton = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        processMonitor2 = new nii.alloe.gui.ProcessMonitor();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alloe");
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Corpus Indexer"));
        openCorpusTextFile.setText("Open Text File");
        openCorpusTextFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openCorpusTextFileActionPerformed(evt);
            }
        });

        openCorpusTermSet.setText("Open Term Set");
        openCorpusTermSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openCorpusTermSetActionPerformed(evt);
            }
        });

        textFileLabel.setText("Text File: Not Loaded");

        termSetLabel.setText("Term Set: Not Loaded");

        indexerProgressMonitor.setProcessCompletedText("Corpus loaded");
        indexerProgressMonitor.setProcessNotStartedText("Corpus not loaded");

        indexLocationLabel.setText("Index Location: Not Loaded");

        setIndexButton.setText("Set Index");
        setIndexButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setIndexButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(indexerProgressMonitor, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(termSetLabel)
                            .addComponent(textFileLabel)
                            .addComponent(indexLocationLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(setIndexButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(openCorpusTextFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(openCorpusTermSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFileLabel)
                    .addComponent(openCorpusTextFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openCorpusTermSet)
                    .addComponent(termSetLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(indexLocationLabel)
                    .addComponent(setIndexButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(indexerProgressMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Corpus"));
        openIndexedCorpus.setText("Open Corpus");
        openIndexedCorpus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openIndexedCorpusActionPerformed(evt);
            }
        });

        saveIndexedCorpus.setText("Save Corpus");
        saveIndexedCorpus.setEnabled(false);
        saveIndexedCorpus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveIndexedCorpusActionPerformed(evt);
            }
        });

        corpusDisplay.setAutoCreateRowSorter(true);
        corpusDisplay.setModel(getCorpusDisplayTableModel());
        corpusDisplayScroll.setViewportView(corpusDisplay);

        corpusTotalLabel.setText("Total Contexts: 0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(corpusDisplayScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(openIndexedCorpus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveIndexedCorpus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(corpusTotalLabel)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openIndexedCorpus)
                    .addComponent(saveIndexedCorpus)
                    .addComponent(corpusTotalLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(corpusDisplayScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jTabbedPane1.addTab("Corpus", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Generate Patterns"));
        termPairSetLabel.setText("Term Pair Set:");
        termPairSetLabel.setEnabled(false);

        openTermPairSet.setText("Open Term Pair Set");
        openTermPairSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openTermPairSetActionPerformed(evt);
            }
        });

        patternGeneratorRelationship.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "New..." }));
        patternGeneratorRelationship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patternGeneratorRelationshipActionPerformed(evt);
            }
        });

        jLabel2.setText("Relationship:");

        patternGeneratorProgressMonitor.setProcessCompletedText("Pattern Set Generated");
        patternGeneratorProgressMonitor.setProcessNotStartedText("Ready");

        patternBuilderMetric.setModel(new DefaultComboBoxModel(PatternMetricFactory.getPatternMetrics()));
        patternBuilderMetric.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patternBuilderMetricActionPerformed(evt);
            }
        });

        jLabel3.setText("Metric::");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(patternGeneratorProgressMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patternGeneratorRelationship, 0, 353, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(termPairSetLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                        .addComponent(openTermPairSet))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patternBuilderMetric, 0, 390, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(patternGeneratorRelationship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(termPairSetLabel)
                    .addComponent(openTermPairSet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(patternBuilderMetric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patternGeneratorProgressMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Pattern Sets"));
        patternViewerRelationshipLabel.setText("Relationship:");
        patternViewerRelationshipLabel.setEnabled(false);

        patternViewerRelationship.setEnabled(false);
        patternViewerRelationship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patternViewerRelationshipActionPerformed(evt);
            }
        });

        openPatternSet.setText("Open Pattern Set");
        openPatternSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openPatternSetActionPerformed(evt);
            }
        });

        savePatternSet.setText("Save Pattern Set");
        savePatternSet.setEnabled(false);
        savePatternSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePatternSetActionPerformed(evt);
            }
        });

        totalPatternsLabel.setText("Total Patterns:");

        patternTable.setAutoCreateRowSorter(true);
        patternTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pattern", "Score"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(patternTable);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(patternViewerRelationshipLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patternViewerRelationship, 0, 353, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(openPatternSet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(savePatternSet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalPatternsLabel)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patternViewerRelationshipLabel)
                    .addComponent(patternViewerRelationship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openPatternSet)
                    .addComponent(savePatternSet)
                    .addComponent(totalPatternsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jTabbedPane1.addTab("Patterns", jPanel2);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Feature Vector Former"));
        jLabel1.setText("Relationship:");

        featureVectorRelationship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                featureVectorRelationshipActionPerformed(evt);
            }
        });

        openDataSet.setText("Open Vectors");
        openDataSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openDataSetActionPerformed(evt);
            }
        });

        saveDataSet.setText("Save Vectors");
        saveDataSet.setEnabled(false);
        saveDataSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDataSetActionPerformed(evt);
            }
        });

        featureVectorFormerMonitor.setProcessCompletedText("Feature Vectors Loaded");
        featureVectorFormerMonitor.setProcessNotStartedText("Feature Vectors not Loaded");

        featureVectorTermPairLabel.setText("Term Pair Set:");

        featureOpenTermPairs.setText("Open Term Pair Set");
        featureOpenTermPairs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                featureOpenTermPairsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(featureVectorFormerMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(featureVectorTermPairLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(featureOpenTermPairs))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(featureVectorRelationship, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(openDataSet)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(saveDataSet))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(featureVectorRelationship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openDataSet)
                    .addComponent(saveDataSet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(featureOpenTermPairs)
                    .addComponent(featureVectorTermPairLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(featureVectorFormerMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Train Classifier"));
        wekaOutput.setColumns(20);
        wekaOutput.setEditable(false);
        wekaOutput.setRows(5);
        wekaOutput.setToolTipText("WEKA Output");
        jScrollPane2.setViewportView(wekaOutput);

        classifier.setModel(new DefaultComboBoxModel(getClassifierNames()));
        classifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classifierActionPerformed(evt);
            }
        });

        jLabel5.setText("Classifier:");

        jLabel6.setText("Parameters:");

        saveClassifierButton.setText("Save Classifier");
        saveClassifierButton.setEnabled(false);

        openClassifierButton.setText("Open Classifier");

        startTrainingButton.setText("Start Training");
        startTrainingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTrainingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(classifier, 0, 119, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(classifierParameters, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(startTrainingButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(openClassifierButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveClassifierButton)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(classifierParameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(classifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveClassifierButton)
                    .addComponent(openClassifierButton)
                    .addComponent(startTrainingButton))
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Create Model"));

        jLabel7.setText("Logic:");

        jButton6.setText("Open Logic");

        jButton7.setText("Compare to Term Pair Set");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                        .addComponent(jButton6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addContainerGap(275, Short.MAX_VALUE)
                        .addComponent(jButton7))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(processMonitor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(processMonitor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jTabbedPane1.addTab("Classification", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startTrainingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTrainingButtonActionPerformed
        try {
            Iterator<Map.Entry<String,Instances>> ei = dataSet.instances.entrySet().iterator();
            while(ei.hasNext()) {
                Map.Entry<String,Instances> ei2 = ei.next();
                String relationship = ei2.getKey();
                Instances instances = ei2.getValue();
                instances.setClassIndex(instances.numAttributes()-1);
                String[] opts = new String[1];
                opts[0] = classifierParameters.getText();
                String s = classifier.getSelectedItem().toString();
                Classifier c = Classifier.forName(classifierNameToFullName.get(classifier.getSelectedItem().toString()),
                        opts);
                wekaOutput.append("Building classifier for relationship: " + relationship);
                c.buildClassifier(instances);
                wekaOutput.append(" ...OK!");
            }
        } catch(Exception x) {
            x.printStackTrace();
        }
    }//GEN-LAST:event_startTrainingButtonActionPerformed

    private void classifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classifierActionPerformed
        if(classifier.getSelectedItem().toString().equals("Other")) {
            String displayName = JOptionPane.showInputDialog(this,"Enter Display Name");
            if(displayName == null)
                return;
            // TODO destroy duplication
            String className = "";
            boolean classOK = false;
            while(className != null && !classOK) {
                className = JOptionPane.showInputDialog(this,"Enter Class Name");
            
                if(className == null)
                    return;
                try {
                    classOK = weka.classifiers.Classifier.class.isAssignableFrom(Class.forName(className));
                } catch(ClassNotFoundException x) {
                    classOK = false;
                }
                
                if(!classOK) {
                    JOptionPane.showMessageDialog(this,"Please enter a class name. Example: \"weka.classifiers.bayes.NaiveBayes\"","Invalid classifier name or classifier not found", JOptionPane.ERROR_MESSAGE);
                }
            }
            if(className != null) {
                classifierNameToFullName.put(displayName,className);
                DefaultComboBoxModel dcbm = (DefaultComboBoxModel)classifier.getModel();
                dcbm.insertElementAt(displayName,dcbm.getIndexOf("Other"));
                classifier.setSelectedItem(displayName);
            }
        }
        classifierParameters.setText("");
    }//GEN-LAST:event_classifierActionPerformed

    private void saveDataSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDataSetActionPerformed
        if(fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(fileChooser.getSelectedFile()));
                oos.writeObject(dataSet);
                oos.close();
            } catch(IOException x) {
                JOptionPane.showMessageDialog(this, x.getMessage(), "Could not save data set", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_saveDataSetActionPerformed

    private void openDataSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openDataSetActionPerformed
        if(fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                ObjectInputStream ois = new ObjectInputStream(new FileInputStream(fileChooser.getSelectedFile()));
                Object o = ois.readObject();
                if(!(o instanceof DataSet)) {
                    JOptionPane.showMessageDialog(this, "Invalid Format", "Could not open data set", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                dataSet = (DataSet)o;
                featureVectorRelationship.setModel(new DefaultComboBoxModel(dataSet.instances.keySet().toArray()));
                saveDataSet.setEnabled(true);
            } catch(IOException x) {
                JOptionPane.showMessageDialog(this, x.getMessage(), "Could not open data set", JOptionPane.ERROR_MESSAGE);
            } catch(ClassNotFoundException x) {
                JOptionPane.showMessageDialog(this, x.getMessage(), "Could not open data set", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_openDataSetActionPerformed

    private class FeatureVectorListener implements AlloeProgressListener {
        public void progressChange(double newProgress) {
            
        }
    
    
        public void finished() {
            saveDataSet.setEnabled(true);
        }
    }
    
    private void initFeatureVectorProcess(String rel) {
        if(!featureVectorProcess.containsKey(rel)) {
            try {
                ObjectInputStream ios = new ObjectInputStream(new FileInputStream(fvTermSetFileName.get(rel)));
                Object o = ios.readObject();
                if(!(o instanceof TermPairSet)) {
                    JOptionPane.showMessageDialog(this, "Invalid format", "Could not open term set", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                FeatureVectorFormer fvf = new FeatureVectorFormer(rel,patternSets.get(rel),corpus);
                fvf.dataSet = dataSet;
                featureVectorProcess.put(rel,fvf);
                if(fvListener == null)
                    fvListener = new FeatureVectorListener();
                fvf.addProgressListener(fvListener);
                featureVectorFormerMonitor.setProcess(fvf);
            } catch(IOException x) {
                JOptionPane.showMessageDialog(this, x.getMessage(), "Could not open term set", JOptionPane.ERROR_MESSAGE);
            } catch(ClassNotFoundException x) {
                JOptionPane.showMessageDialog(this, x.getMessage(), "Could not open term set", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void featureOpenTermPairsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_featureOpenTermPairsActionPerformed
        if(fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            String rel = featureVectorRelationship.getSelectedItem().toString();
            fvTermSetFileName.put(rel,
                    fileChooser.getSelectedFile().getAbsolutePath());
            featureVectorTermPairLabel.setText("Term Pair Set: " + fileChooser.getSelectedFile().getPath());
            if(corpus != null && patternSets.get(rel) != null) {
                initFeatureVectorProcess(rel);
            }
        }
    }//GEN-LAST:event_featureOpenTermPairsActionPerformed

    private void featureVectorRelationshipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_featureVectorRelationshipActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_featureVectorRelationshipActionPerformed

    private HashMap<String,String> classifierNameToFullName;
    
    public Vector<String> getClassifierNames() {
        Vector<String> r = new Vector<String>(9);
        classifierNameToFullName = new HashMap<String,String>(8);
        classifierNameToFullName.put("Bayesian Network","weka.classifiers.bayes.BayesNet");
        classifierNameToFullName.put("Decision Tree","weka.classifiers.trees.J48");
        classifierNameToFullName.put("Rule Learner","weka.classifiers.rules.JRip");
        classifierNameToFullName.put("Linear Regression","weka.classifiers.functions.LinearRegression");
        classifierNameToFullName.put("Multilayer Perceptron","weka.classifiers.functions.MultilayerPerceptron");
        classifierNameToFullName.put("Naive Bayes","weka.classifiers.bayes.NaiveBayes");
        classifierNameToFullName.put("SVM","weka.classifiers.functions.SMO");
        classifierNameToFullName.put("SVM Regression","weka.classifiers.functions.SMOreg");
        
        r.add("SVM Regression");
        r.add("SVM");
        r.add("Naive Bayes");
        r.add("Bayesian Network");
        r.add("Multilayer Perceptron");
        r.add("Linear Regression");
        r.add("Rule Learner");
        r.add("Decision Tree");
        r.add("Other");
        
        return r;
    }
    
    
    private void patternViewerRelationshipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patternViewerRelationshipActionPerformed
        onPatternSetLoad(patternViewerRelationship.getSelectedItem().toString(),false);
    }//GEN-LAST:event_patternViewerRelationshipActionPerformed
    
    private void onPatternSetLoad(String relationship) { onPatternSetLoad(relationship,true); }
    private void onPatternSetLoad(String relationship, boolean select) {
        DefaultComboBoxModel dcbm = (DefaultComboBoxModel)patternViewerRelationship.getModel();
        if(dcbm.getIndexOf(relationship) == -1) {
            dcbm.addElement(relationship);
        }
        dcbm = (DefaultComboBoxModel)featureVectorRelationship.getModel();
        if(dcbm.getIndexOf(relationship) == -1) {
            dcbm.addElement(relationship);
        }
        if(select)
            patternViewerRelationship.setSelectedItem(relationship);
        patternViewerRelationship.setEnabled(true);
        patternViewerRelationshipLabel.setEnabled(true);
        savePatternSet.setEnabled(true);
        PatternSet ps = patternSets.get(relationship);
        if(ps == null)
            return;
        
        totalPatternsLabel.setText("Total Patterns: " + ps.size());
        
        DefaultTableModel dtm = (DefaultTableModel)patternTable.getModel();
        Object[][] o = new Object[ps.size()][2];
        DecimalFormat df = new DecimalFormat("0.00000000");
        Iterator<Map.Entry<Pattern,Double>> iter = ps.entrySet().iterator();
        int i = 0;
        while(iter.hasNext()) {
            Map.Entry<Pattern,Double> e = iter.next();
            o[i][0] = e.getKey().toString();
            o[i++][1] = df.format(e.getValue().doubleValue());
        }
        String [] s = { "Pattern", "Score" };
        dtm.setDataVector(o,s);
    }
    
    private class PatternGeneratorListener implements PatternBuilderListener {
        private String getRelationship() { return ((PatternBuilder)patternGeneratorProgressMonitor.getProcess()).getRelationship(); }
        
        /** Called whenever progress is made
         * @param newProgress The new progress percentage (as double between 0 and 1) */
        public void progressChange(double newProgress) {}
        
        /** Called when the process finishes */
        public void finished() { 
            patternSets.put(getRelationship(), patternBuilderProcess.get(getRelationship()).patternScores);
            onPatternSetLoad(getRelationship()); }
        
        public void patternGenerated(Pattern p, double score) {
            if(patternViewerRelationship.getSelectedItem().toString().equals(getRelationship())) {
                DefaultTableModel dtm = (DefaultTableModel)patternTable.getModel();
                Object[] row = new Object[2];
                row[0] = p.toString();
                NumberFormat df = new DecimalFormat("0.00000000");
                row[1] = df.format(score);
                dtm.addRow(row);
                totalPatternsLabel.setText("Total Patterns: " + patternBuilderProcess.get(getRelationship()).patternScores.size());
            }
        }
    }
    
    private void savePatternSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePatternSetActionPerformed
        if(fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(fileChooser.getSelectedFile()));
                oos.writeObject(patternSets.get(patternViewerRelationship.getSelectedItem().toString()));
                oos.close();
            } catch(IOException x) {
                JOptionPane.showMessageDialog(this, x.getMessage(), "Could not save pattern set", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_savePatternSetActionPerformed
    
    private void openPatternSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openPatternSetActionPerformed
        if(fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                ObjectInputStream ois = new ObjectInputStream(new FileInputStream(fileChooser.getSelectedFile()));
                Object o = ois.readObject();
                if(!(o instanceof PatternSet)) {
                    JOptionPane.showMessageDialog(this, "Invalid format", "Could not open pattern set", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                PatternSet ps = (PatternSet)o;
                if(ps.getRelationship() == null) {
                    throw new NullPointerException();
                }
                patternSets.put(ps.getRelationship(),ps);
                onPatternSetLoad(ps.getRelationship());
            } catch(IOException x) {
                JOptionPane.showMessageDialog(this, x.getMessage(), "Could not open pattern set", JOptionPane.ERROR_MESSAGE);
            } catch(ClassNotFoundException x) {
                JOptionPane.showMessageDialog(this, x.getMessage(), "Could not open pattern set", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_openPatternSetActionPerformed
    
    private void patternBuilderMetricActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patternBuilderMetricActionPerformed
        PatternBuilder pb = patternBuilderProcess.get(patternGeneratorRelationship.getSelectedItem().toString());
        if(pb != null && !pb.isRunning()) {
            pb.setPatternMetric(patternBuilderMetric.getSelectedItem().toString());
        }
    }//GEN-LAST:event_patternBuilderMetricActionPerformed
    
    private void initPatternBuilderProcess(String name) {
        if(!patternBuilderProcess.containsKey(name)) {
            try {
                ObjectInputStream ios = new ObjectInputStream(new FileInputStream(termSetFileName.get(name)));
                Object o = ios.readObject();
                if(!(o instanceof TermPairSet)) {
                    JOptionPane.showMessageDialog(this, "Invalid format", "Could not open term set", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                PatternBuilder pb =  new PatternBuilder(corpus, (TermPairSet)o,
                        (String)patternBuilderMetric.getSelectedItem(), name);
                patternBuilderProcess.put(name,pb);
                if(pbListener == null)
                    pbListener = new PatternGeneratorListener();
                pb.addProgressListener(pbListener);
                patternGeneratorProgressMonitor.setProcess(pb);
            } catch(IOException x) {
                JOptionPane.showMessageDialog(this, x.getMessage(), "Could not open term set", JOptionPane.ERROR_MESSAGE);
            } catch(ClassNotFoundException x) {
                JOptionPane.showMessageDialog(this, x.getMessage(), "Could not open term set", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void openTermPairSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openTermPairSetActionPerformed
        if(fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            termSetFileName.put(patternGeneratorRelationship.getSelectedItem().toString(),
                    fileChooser.getSelectedFile().getAbsolutePath());
            termPairSetLabel.setText("Term Pair Set: " + fileChooser.getSelectedFile().getPath());
            if(corpus != null) {
                initPatternBuilderProcess(patternGeneratorRelationship.getSelectedItem().toString());
            }
        }
    }//GEN-LAST:event_openTermPairSetActionPerformed
    
    private void patternGeneratorRelationshipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patternGeneratorRelationshipActionPerformed
        if(patternGeneratorRelationship.getSelectedItem().equals("New...")) {
            String name = JOptionPane.showInputDialog(this, "New Relation", "");
            ((DefaultComboBoxModel)patternGeneratorRelationship.getModel()).insertElementAt(name,0);
            ((DefaultComboBoxModel)patternViewerRelationship.getModel()).insertElementAt(name,0);
            ((DefaultComboBoxModel)featureVectorRelationship.getModel()).insertElementAt(name,0);
            if(patternGeneratorRelationship.getItemAt(1).equals("")) {
                patternGeneratorRelationship.removeItemAt(1);
            }
            
            patternGeneratorRelationship.setSelectedItem(name);
            patternViewerRelationship.setSelectedItem(name);
        }
        
        termPairSetLabel.setEnabled(true);
        String s = termSetFileName.get(patternGeneratorRelationship.getSelectedItem().toString());
        termPairSetLabel.setText("Term Pair Set: " + (s == null ? "" : s));
        openTermPairSet.setEnabled(true);
        PatternBuilder pb = (PatternBuilder)patternGeneratorProgressMonitor.getProcess();
        if(pb == null || !pb.isRunning())
            patternGeneratorProgressMonitor.setProcess(patternBuilderProcess.get(patternGeneratorRelationship.getSelectedItem().toString()));
        
    }//GEN-LAST:event_patternGeneratorRelationshipActionPerformed
    
    private void saveIndexedCorpusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveIndexedCorpusActionPerformed
        if(fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(fileChooser.getSelectedFile()));
                oos.writeObject(corpus);
                oos.close();
            } catch(IOException x) {
                JOptionPane.showMessageDialog(this, x.getMessage(), "Could not save corpus", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_saveIndexedCorpusActionPerformed
    
    private void setIndexButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setIndexButtonActionPerformed
        int oldFMS = fileChooser.getFileSelectionMode();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.setAcceptAllFileFilterUsed(false);
        if(fileChooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) {
            fileChooser.setFileSelectionMode(oldFMS);
            fileChooser.setAcceptAllFileFilterUsed(true);
            return;
        }
        fileChooser.setFileSelectionMode(oldFMS);
        fileChooser.setAcceptAllFileFilterUsed(true);
        corpusIndexFile = fileChooser.getSelectedFile().getAbsolutePath();
        indexLocationLabel.setText("Index Location: " + fileChooser.getSelectedFile().getPath());
        if(corpusTextFile.length() > 0 && corpusTermSetFile.length() > 0&&
                corpusIndexFile.length() > 0) {
            prepareCorpusLoader();
        }
    }//GEN-LAST:event_setIndexButtonActionPerformed
    
    private void prepareCorpusLoader() {
        try {
            ObjectInputStream ois = new ObjectInputStream(new FileInputStream(corpusTermSetFile));
            Object o = ois.readObject();
            if(!(o instanceof TermList)) {
                JOptionPane.showMessageDialog(this, "Invalid File Format", "Could not open term set", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            corpusLoader = new CorpusLoader((TermList)o, corpusTextFile, corpusIndexFile);
            indexerProgressMonitor.setProcess(corpusLoader);
            if(clProgListener == null)
                clProgListener = new CorpusLoaderProgressListener();
            corpusLoader.addProgressListener(clProgListener);
            
        } catch(IOException x) {
            JOptionPane.showMessageDialog(this, x.getMessage(), "Could not initialize indexer", JOptionPane.ERROR_MESSAGE);
        } catch(ClassNotFoundException x) {
            JOptionPane.showMessageDialog(this, x.getMessage(), "Could not initialize indexer", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private class CorpusTableModel extends AbstractTableModel {
        public int getColumnCount() { return 2; }
        public int getRowCount() { return corpus == null ? 0 : corpus.terms.size(); }
        public Object getValueAt(int i, int j) {
            if(j == 0) {
                return corpus.terms.get(i);
            } else if(j == 1) {
                return corpus.getHitsForTerm(corpus.terms.get(i));
            } else {
                assert false;
                return null;
            }
        }
        public String getColumnName(int j) {
            if(j == 0) {
                return "Term";
            } else if(j == 1) {
                return "Frequency";
            } else {
                assert false;
                return null;
            }
        }
        
        public Class getColumnClass(int j) {
            if(j == 0)
                return String.class;
            if(j == 1)
                return Integer.class;
            else
                return null;
        }
    }
    
    private void onCorpusLoad() {
        corpusTotalLabel.setText("Total Contexts: " + corpus.getTotalDocs());
        corpusDisplayTableModel.fireTableDataChanged();
        corpusDisplay.revalidate();
        saveIndexedCorpus.setEnabled(true);
        dataSet = new DataSet(corpus.terms);
    }
    
    private void openIndexedCorpusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openIndexedCorpusActionPerformed
        try {
            if(fileChooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION)
                return;
            ObjectInputStream ois = new ObjectInputStream(new FileInputStream(fileChooser.getSelectedFile()));
            Object o = ois.readObject();
            if(!(o instanceof Corpus)) {
                JOptionPane.showMessageDialog(this, "Invalid Format", "Could not load corpus", JOptionPane.ERROR_MESSAGE);
                return;
            }
            corpus = (Corpus)o;
            onCorpusLoad();
        } catch(IOException x) {
            JOptionPane.showMessageDialog(this, x.getMessage(), "Could not load corpus", JOptionPane.ERROR_MESSAGE);
        } catch(ClassNotFoundException x) {
            JOptionPane.showMessageDialog(this, x.getMessage(), "Could not load corpus", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_openIndexedCorpusActionPerformed
    
    private class CorpusLoaderProgressListener implements AlloeProgressListener {
        public void finished() {
            //corpus = corpusLoader.corpus;
            AlloeProcess p = indexerProgressMonitor.getProcess();
            assert p instanceof CorpusLoader;
            corpus = ((CorpusLoader)p).corpus;
            onCorpusLoad();
        }
        public void progressChange(double newProgress) {
        }
    }
    
    private void openCorpusTermSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openCorpusTermSetActionPerformed
        if(fileChooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION)
            return;
        corpusTermSetFile = fileChooser.getSelectedFile().getAbsolutePath();
        termSetLabel.setText("Term Set: " + fileChooser.getSelectedFile().getPath());
        if(corpusTextFile.length() > 0 && corpusTermSetFile.length() > 0 &&
                corpusIndexFile.length() > 0) {
            prepareCorpusLoader();
        }
    }//GEN-LAST:event_openCorpusTermSetActionPerformed
    
    private void openCorpusTextFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openCorpusTextFileActionPerformed
        if(fileChooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION)
            return;
        corpusTextFile = fileChooser.getSelectedFile().getAbsolutePath();
        textFileLabel.setText("Text File: " + fileChooser.getSelectedFile().getPath());
        if(corpusTextFile.length() > 0 && corpusTermSetFile.length() > 0&&
                corpusIndexFile.length() > 0) {
            prepareCorpusLoader();
        }
    }//GEN-LAST:event_openCorpusTextFileActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlloeMain().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox classifier;
    private javax.swing.JTextField classifierParameters;
    private javax.swing.ButtonGroup corpusAction;
    private javax.swing.JTable corpusDisplay;
    private javax.swing.JScrollPane corpusDisplayScroll;
    private javax.swing.JLabel corpusTotalLabel;
    private javax.swing.JButton featureOpenTermPairs;
    private nii.alloe.gui.ProcessMonitor featureVectorFormerMonitor;
    private javax.swing.JComboBox featureVectorRelationship;
    private javax.swing.JLabel featureVectorTermPairLabel;
    private javax.swing.JLabel indexLocationLabel;
    private nii.alloe.gui.ProcessMonitor indexerProgressMonitor;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton openClassifierButton;
    private javax.swing.JButton openCorpusTermSet;
    private javax.swing.JButton openCorpusTextFile;
    private javax.swing.JButton openDataSet;
    private javax.swing.JButton openIndexedCorpus;
    private javax.swing.JButton openPatternSet;
    private javax.swing.JButton openTermPairSet;
    private javax.swing.JComboBox patternBuilderMetric;
    private nii.alloe.gui.ProcessMonitor patternGeneratorProgressMonitor;
    private javax.swing.JComboBox patternGeneratorRelationship;
    private javax.swing.JTable patternTable;
    private javax.swing.JComboBox patternViewerRelationship;
    private javax.swing.JLabel patternViewerRelationshipLabel;
    private nii.alloe.gui.ProcessMonitor processMonitor2;
    private javax.swing.JButton saveClassifierButton;
    private javax.swing.JButton saveDataSet;
    private javax.swing.JButton saveIndexedCorpus;
    private javax.swing.JButton savePatternSet;
    private javax.swing.JButton setIndexButton;
    private javax.swing.JButton startTrainingButton;
    private javax.swing.JLabel termPairSetLabel;
    private javax.swing.JLabel termSetLabel;
    private javax.swing.JLabel textFileLabel;
    private javax.swing.JLabel totalPatternsLabel;
    private javax.swing.JTextArea wekaOutput;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Holds value of property corpusDisplayTableModel.
     */
    private CorpusTableModel corpusDisplayTableModel;
    
    /**
     * Getter for property corpusDisplayTableModel.
     * @return Value of property corpusDisplayTableModel.
     */
    public CorpusTableModel getCorpusDisplayTableModel() {
        if(corpusDisplayTableModel != null)
            return this.corpusDisplayTableModel;
        else
            return corpusDisplayTableModel = new CorpusTableModel();
    }
    
    /**
     * Setter for property corpusDisplayTableModel.
     * @param corpusDisplayTableModel New value of property corpusDisplayTableModel.
     */
    public void setCorpusDisplayTableModel(CorpusTableModel corpusDisplayTableModel) {
        this.corpusDisplayTableModel = corpusDisplayTableModel;
    }
    
}
